var num1 = 345;
var num2 = 22;
var num3 = 100;
var num4 = 9935;
var string1 = "Hello";
var string2 = "World";
var string3 = "!";
var isOnline = true;
var isOffline = false;
var undef = [];
console.log("The first number is " + num1);
console.log("The first number is " + num2);
console.log("The first number is " + num3);
console.log("The first number is " + num4);
console.log("The first string is " + string1);
console.log("The first string is " + string2);
console.log("The first string is " + string3);
console.log("The first boolean is " + isOnline);
console.log("The second boolean is " + isOffline);
console.log("The final variable is " + undef);